import FWCore.ParameterSet.Config as cms
import copy

leptonssize = cms.untracked.int32(5)
jetssize = cms.untracked.int32(20)

mulabel = cms.string("muons")
elelabel = cms.string("electrons")
jetAK4label = cms.string("jetsAK4")
jetAK8label = cms.string("jetsAK8")
jetCmsTopTaglabel = cms.string("jetsCmsTopTag")
subjetAK8label = cms.string("subjetsAK8")
subjetCmsTopTaglabel = cms.string("subjetsCmsTopTag")
metlabel = cms.string("met")

DMTreesDumper = cms.EDAnalyzer(
    'DMAnalysisTreeMaker',
    lhes = cms.InputTag('source'),
    muLabel = mulabel,
    eleLabel = elelabel,
    jetsAK4Label = jetAK4label,
    jetsAK8Label = jetAK8label,
    jetsCmsTopTagLabel = jetCmsTopTaglabel,
    subjetsAK8Label = subjetAK8label,
    subjetsCmsTopTagLabel = subjetCmsTopTaglabel,
    metLabel = metlabel,
    physicsObjects = cms.VPSet(
        cms.PSet(
            label = elelabel,
            prefix = cms.string("el"),
            maxInstances = leptonssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("electrons","elMass"),
                cms.InputTag("electrons","elPt"),
                cms.InputTag("electrons","elEta"),
                cms.InputTag("electrons","elY"),
                cms.InputTag("electrons","elPhi"),
                cms.InputTag("electrons","elE"),
                cms.InputTag("electrons","elCharge"),
                # EleVars
                cms.InputTag("electrons","elIso03"),
                cms.InputTag("electrons","elD0"),
                cms.InputTag("electrons","elDz"),
                cms.InputTag("electrons","eldEtaIn"),
                cms.InputTag("electrons","eldPhiIn"),
                cms.InputTag("electrons","elHoE"),
                cms.InputTag("electrons","elfull5x5siee"),
                cms.InputTag("electrons","elooEmooP"),
                cms.InputTag("electrons","elmissHits"),
                cms.InputTag("electrons","elhasMatchedConVeto"),
                cms.InputTag("electrons","elisEB"),
                cms.InputTag("electrons","elisVeto"),
                cms.InputTag("electrons","elisLoose"),
                cms.InputTag("electrons","elisTight"),
                cms.InputTag("electrons","elisMedium"),
            ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),
        cms.PSet(
            label = mulabel,
            prefix = cms.string("mu"),
            maxInstances = leptonssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("muons","muMass"),
                cms.InputTag("muons","muPt"),
                cms.InputTag("muons","muEta"),
                cms.InputTag("muons","muY"),
                cms.InputTag("muons","muPhi"),
                cms.InputTag("muons","muE"),
                cms.InputTag("muons","muCharge"),
                # MuonVars
                cms.InputTag("muons","muIso03"),
                cms.InputTag("muons","muD0"),
                cms.InputTag("muons","muD0err"),
                cms.InputTag("muons","muDz"),
                cms.InputTag("muons","muDzerr"),
                ### the following variables need have track embedded in the pat::muon
                cms.InputTag("muons","muIsLooseMuon"),
                cms.InputTag("muons","muIsSoftMuon"),
                cms.InputTag("muons","muIsTightMuon"),
                ## variables used in ID
                ### LOOSE
                cms.InputTag("muons","muIsPFMuon"),
                cms.InputTag("muons","muIsGlobalMuon"),
                cms.InputTag("muons","muIsTrackerMuon"),
                ### TIGHT
                cms.InputTag("muons","muGlbTrkNormChi2"),
                cms.InputTag("muons","muNumberValidMuonHits"),
                cms.InputTag("muons","muNumberMatchedStations"),
                cms.InputTag("muons","muNumberValidPixelHits"),
                cms.InputTag("muons","muNumberTrackerLayers"),
                ### SOFT
                cms.InputTag("muons","muNumberOfValidTrackerHits"),
                cms.InputTag("muons","muNumberOfPixelLayers"),
                cms.InputTag("muons","muInTrkNormChi2"),
                ## variables used in isolation
                cms.InputTag("muons","muSumChargedHadronPt"),
                cms.InputTag("muons","muSumNeutralHadronPt"),
                cms.InputTag("muons","muSumPhotonPt"),
                cms.InputTag("muons","muSumPUPt"),
                ### genLepton
                cms.InputTag("muons","muGenMuonY"),
                cms.InputTag("muons","muGenMuonEta"),
                cms.InputTag("muons","muGenMuonPhi"),
                cms.InputTag("muons","muGenMuonPt"),
                cms.InputTag("muons","muGenMuonE"),
                cms.InputTag("muons","muGenMuonCharge"),
                ### trigger matching
                cms.InputTag("muons","muHLTmuonDeltaR"),
                cms.InputTag("muons","muHLTmuonPt"),
                cms.InputTag("muons","muHLTmuonEta"),
                cms.InputTag("muons","muHLTmuonPhi"),
                cms.InputTag("muons","muHLTmuonE"),
            ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),
        cms.PSet(
            label = jetAK4label,
            prefix = cms.string("jetAK4"),
            maxInstances = jetssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("jetsAK4","jetAK4Mass"),
                cms.InputTag("jetsAK4","jetAK4Pt"),
                cms.InputTag("jetsAK4","jetAK4Eta"),
                cms.InputTag("jetsAK4","jetAK4Y"),
                cms.InputTag("jetsAK4","jetAK4Phi"),
                cms.InputTag("jetsAK4","jetAK4E"),
                cms.InputTag("jetsAK4","jetAK4Charge"),
                # jetVars
                ### B-TAGGING
                cms.InputTag("jetsAK4","jetAK4CSV"),
                cms.InputTag("jetsAK4","jetAK4CSVV1"),
                ### GEN PARTON
                cms.InputTag("jetsAK4","jetAK4GenPartonY"),
                cms.InputTag("jetsAK4","jetAK4GenPartonEta"),
                cms.InputTag("jetsAK4","jetAK4GenPartonPhi"),
                cms.InputTag("jetsAK4","jetAK4GenPartonPt"),
                cms.InputTag("jetsAK4","jetAK4GenPartonE"),
                cms.InputTag("jetsAK4","jetAK4GenPartonCharge"),
                ###
                cms.InputTag("jetsAK4","jetAK4PartonFlavour"),
                cms.InputTag("jetsAK4","jetAK4HadronFlavour"),
                ### GEN JET
                cms.InputTag("jetsAK4","jetAK4GenJetY"),
                cms.InputTag("jetsAK4","jetAK4GenJetEta"),
                cms.InputTag("jetsAK4","jetAK4GenJetPhi"),
                cms.InputTag("jetsAK4","jetAK4GenJetPt"),
                cms.InputTag("jetsAK4","jetAK4GenJetE"),
                cms.InputTag("jetsAK4","jetAK4GenJetCharge"),
                ### TRIGGER MATHING
                cms.InputTag("jetsAK4","jetAK4HLTjetEta"),
                cms.InputTag("jetsAK4","jetAK4HLTjetPhi"),
                cms.InputTag("jetsAK4","jetAK4HLTjetPt"),
                cms.InputTag("jetsAK4","jetAK4HLTjetE"),
                cms.InputTag("jetsAK4","jetAK4HLTjetDeltaR"),
                ### CONSTITUENTS
                cms.InputTag("jetsAK4","jetAK4muonMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4PhotonEnergy"),
                cms.InputTag("jetsAK4","jetAK4ElectronEnergy"),
                cms.InputTag("jetsAK4","jetAK4MuonEnergy"),
                cms.InputTag("jetsAK4","jetAK4HFHadronEnergy"),
                cms.InputTag("jetsAK4","jetAK4HFEMEnergy"),
                cms.InputTag("jetsAK4","jetAK4ChargedHadronMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4numberOfDaughters"),
                cms.InputTag("jetsAK4","jetAK4chargedMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4neutralHadronMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4neutralHadronEnergyFraction"),
                cms.InputTag("jetsAK4","jetAK4neutralEmEnergyFraction"),
                cms.InputTag("jetsAK4","jetAK4chargedEmEnergyFraction"),
                cms.InputTag("jetsAK4","jetAK4chargedHadronEnergyFraction"),
                cms.InputTag("jetsAK4","jetAK4photonMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4electronMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4HFHadronMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4HFEMMultiplicity"),
                cms.InputTag("jetsAK4","jetAK4ChargeMuEnergy"),
                cms.InputTag("jetsAK4","jetAK4neutralMultiplicity"),
                #### FOR JEC
                cms.InputTag("jetsAK4","jetAK4jecFactor0"),
                #### FOR SYSTEMATICS
                cms.InputTag("jetsAK4","jetAK4SmearedPt"),
                cms.InputTag("jetsAK4","jetAK4SmearedPEta"),
                cms.InputTag("jetsAK4","jetAK4SmearedPhi"),
                cms.InputTag("jetsAK4","jetAK4SmearedE"),
                cms.InputTag("jetsAK4","jetAK4JERup"),
                cms.InputTag("jetsAK4","jetAK4JERdown"),
            ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),
       cms.PSet(
            label = jetAK8label,
            prefix = cms.string("jetAK8"),
            maxInstances = jetssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("jetsAK8","jetAK8Mass"),
                cms.InputTag("jetsAK8","jetAK8Pt"),
                cms.InputTag("jetsAK8","jetAK8Eta"),
                cms.InputTag("jetsAK8","jetAK8Y"),
                cms.InputTag("jetsAK8","jetAK8Phi"),
                cms.InputTag("jetsAK8","jetAK8E"),
                cms.InputTag("jetsAK8","jetAK8Charge"),
                # jetVars
                ### B-TAGGING
                cms.InputTag("jetsAK8","jetAK8CSV"),
                cms.InputTag("jetsAK8","jetAK8CSVV1"),
                ### GEN PARTON
                cms.InputTag("jetsAK8","jetAK8GenPartonY"),
                cms.InputTag("jetsAK8","jetAK8GenPartonEta"),
                cms.InputTag("jetsAK8","jetAK8GenPartonPhi"),
                cms.InputTag("jetsAK8","jetAK8GenPartonPt"),
                cms.InputTag("jetsAK8","jetAK8GenPartonE"),
                cms.InputTag("jetsAK8","jetAK8GenPartonCharge"),
                ###
                cms.InputTag("jetsAK8","jetAK8PartonFlavour"),
                cms.InputTag("jetsAK8","jetAK8HadronFlavour"),
                ### GEN JET
                cms.InputTag("jetsAK8","jetAK8GenJetY"),
                cms.InputTag("jetsAK8","jetAK8GenJetEta"),
                cms.InputTag("jetsAK8","jetAK8GenJetPhi"),
                cms.InputTag("jetsAK8","jetAK8GenJetPt"),
                cms.InputTag("jetsAK8","jetAK8GenJetE"),
                cms.InputTag("jetsAK8","jetAK8GenJetCharge"),
                ### TRIGGER MATHING
                cms.InputTag("jetsAK8","jetAK8HLTjetEta"),
                cms.InputTag("jetsAK8","jetAK8HLTjetPhi"),
                cms.InputTag("jetsAK8","jetAK8HLTjetPt"),
                cms.InputTag("jetsAK8","jetAK8HLTjetE"),
                cms.InputTag("jetsAK8","jetAK8HLTjetDeltaR"),
                ### CONSTITUENTS
                cms.InputTag("jetsAK8","jetAK8muonMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8PhotonEnergy"),
                cms.InputTag("jetsAK8","jetAK8ElectronEnergy"),
                cms.InputTag("jetsAK8","jetAK8MuonEnergy"),
                cms.InputTag("jetsAK8","jetAK8HFHadronEnergy"),
                cms.InputTag("jetsAK8","jetAK8HFEMEnergy"),
                cms.InputTag("jetsAK8","jetAK8ChargedHadronMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8numberOfDaughters"),
                cms.InputTag("jetsAK8","jetAK8chargedMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8neutralHadronMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8neutralHadronEnergyFraction"),
                cms.InputTag("jetsAK8","jetAK8neutralEmEnergyFraction"),
                cms.InputTag("jetsAK8","jetAK8chargedEmEnergyFraction"),
                cms.InputTag("jetsAK8","jetAK8chargedHadronEnergyFraction"),
                cms.InputTag("jetsAK8","jetAK8photonMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8electronMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8HFHadronMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8HFEMMultiplicity"),
                cms.InputTag("jetsAK8","jetAK8ChargeMuEnergy"),
                cms.InputTag("jetsAK8","jetAK8neutralMultiplicity"),
                #### FOR JEC
                cms.InputTag("jetsAK8","jetAK8jecFactor0"),
                #### FOR SYSTEMATICS
                cms.InputTag("jetsAK8","jetAK8SmearedPt"),
                cms.InputTag("jetsAK8","jetAK8SmearedPEta"),
                cms.InputTag("jetsAK8","jetAK8SmearedPhi"),
                cms.InputTag("jetsAK8","jetAK8SmearedE"),
                cms.InputTag("jetsAK8","jetAK8JERup"),
                cms.InputTag("jetsAK8","jetAK8JERdown"),
                # AK8Vars
                cms.InputTag("jetsAK8","jetAK8subjetIndex0"),
                cms.InputTag("jetsAK8","jetAK8subjetIndex1"),
                cms.InputTag("jetsAK8","jetAK8subjetIndex2"),
                cms.InputTag("jetsAK8","jetAK8subjetIndex4"),
                cms.InputTag("jetsAK8","jetAK8tau1"),
                cms.InputTag("jetsAK8","jetAK8tau2"),
                cms.InputTag("jetsAK8","jetAK8tau3"),
                cms.InputTag("jetsAK8","jetAK8trimmedMass"),
                cms.InputTag("jetsAK8","jetAK8prunedMass"),
                cms.InputTag("jetsAK8","jetAK8filteredMass"),
                ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),
       cms.PSet(
            label = jetCmsTopTaglabel,
            prefix = cms.string("jetsCmsTopTag"),
            maxInstances = jetssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagMass"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagPt"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagEta"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagY"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagPhi"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagE"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagCharge"),
                # jetVars
                ### B-TAGGING
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagCSV"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagCSVV1"),
                ### GEN PARTON
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenPartonY"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenPartonEta"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenPartonPhi"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenPartonPt"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenPartonE"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenPartonCharge"),
                ###
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagPartonFlavour"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHadronFlavour"),
                ### GEN JET
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenJetY"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenJetEta"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenJetPhi"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenJetPt"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenJetE"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagGenJetCharge"),
                ### TRIGGER MATHING
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHLTjetEta"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHLTjetPhi"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHLTjetPt"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHLTjetE"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHLTjetDeltaR"),
                ### CONSTITUENTS
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagmuonMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagPhotonEnergy"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagElectronEnergy"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagMuonEnergy"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHFHadronEnergy"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHFEMEnergy"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagChargedHadronMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagnumberOfDaughters"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagchargedMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagneutralHadronMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagneutralHadronEnergyFraction"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagneutralEmEnergyFraction"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagchargedEmEnergyFraction"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagchargedHadronEnergyFraction"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagphotonMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagelectronMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHFHadronMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagHFEMMultiplicity"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagChargeMuEnergy"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagneutralMultiplicity"),
                #### FOR JEC
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagjecFactor0"),
                #### FOR SYSTEMATICS
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagSmearedPt"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagSmearedPEta"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagSmearedPhi"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagSmearedE"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagJERup"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagJERdown"),
                # AK8Vars
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagsubjetIndex0"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagsubjetIndex1"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagsubjetIndex2"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagsubjetIndex4"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagtau1"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagtau2"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagtau3"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagtrimmedMass"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagprunedMass"),
                cms.InputTag("jetsCmsTopTag","jetsCmsTopTagfilteredMass"),
                ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),
       cms.PSet(
            label = subjetAK8label,
            prefix = cms.string("subjetAK8"),
            maxInstances = jetssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("subjetsAK8","subjetAK8Mass"),
                cms.InputTag("subjetsAK8","subjetAK8Pt"),
                cms.InputTag("subjetsAK8","subjetAK8Eta"),
                cms.InputTag("subjetsAK8","subjetAK8Y"),
                cms.InputTag("subjetsAK8","subjetAK8Phi"),
                cms.InputTag("subjetsAK8","subjetAK8E"),
                cms.InputTag("subjetsAK8","subjetAK8Charge"),
                # subjetVars
                ### B-TAGGING
                cms.InputTag("subjetsAK8","subjetAK8CSV"),
                cms.InputTag("subjetsAK8","subjetAK8CSVV1"),
                ### GEN PARTON
                cms.InputTag("subjetsAK8","subjetAK8GenPartonY"),
                cms.InputTag("subjetsAK8","subjetAK8GenPartonEta"),
                cms.InputTag("subjetsAK8","subjetAK8GenPartonPhi"),
                cms.InputTag("subjetsAK8","subjetAK8GenPartonPt"),
                cms.InputTag("subjetsAK8","subjetAK8GenPartonE"),
                cms.InputTag("subjetsAK8","subjetAK8GenPartonCharge"),
                ###
                cms.InputTag("subjetsAK8","subjetAK8PartonFlavour"),
                cms.InputTag("subjetsAK8","subjetAK8HadronFlavour"),
                ### GEN JET
                cms.InputTag("subjetsAK8","subjetAK8GenJetY"),
                cms.InputTag("subjetsAK8","subjetAK8GenJetEta"),
                cms.InputTag("subjetsAK8","subjetAK8GenJetPhi"),
                cms.InputTag("subjetsAK8","subjetAK8GenJetPt"),
                cms.InputTag("subjetsAK8","subjetAK8GenJetE"),
                cms.InputTag("subjetsAK8","subjetAK8GenJetCharge"),
                ### TRIGGER MATHING
                cms.InputTag("subjetsAK8","subjetAK8HLTjetEta"),
                cms.InputTag("subjetsAK8","subjetAK8HLTjetPhi"),
                cms.InputTag("subjetsAK8","subjetAK8HLTjetPt"),
                cms.InputTag("subjetsAK8","subjetAK8HLTjetE"),
                cms.InputTag("subjetsAK8","subjetAK8HLTjetDeltaR"),
                ### CONSTITUENTS
                cms.InputTag("subjetsAK8","subjetAK8muonMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8PhotonEnergy"),
                cms.InputTag("subjetsAK8","subjetAK8ElectronEnergy"),
                cms.InputTag("subjetsAK8","subjetAK8MuonEnergy"),
                cms.InputTag("subjetsAK8","subjetAK8HFHadronEnergy"),
                cms.InputTag("subjetsAK8","subjetAK8HFEMEnergy"),
                cms.InputTag("subjetsAK8","subjetAK8ChargedHadronMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8numberOfDaughters"),
                cms.InputTag("subjetsAK8","subjetAK8chargedMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8neutralHadronMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8neutralHadronEnergyFraction"),
                cms.InputTag("subjetsAK8","subjetAK8neutralEmEnergyFraction"),
                cms.InputTag("subjetsAK8","subjetAK8chargedEmEnergyFraction"),
                cms.InputTag("subjetsAK8","subjetAK8chargedHadronEnergyFraction"),
                cms.InputTag("subjetsAK8","subjetAK8photonMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8electronMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8HFHadronMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8HFEMMultiplicity"),
                cms.InputTag("subjetsAK8","subjetAK8ChargeMuEnergy"),
                cms.InputTag("subjetsAK8","subjetAK8neutralMultiplicity"),
                #### FOR JEC
                cms.InputTag("subjetsAK8","subjetAK8jecFactor0"),
                #### FOR SYSTEMATICS
                cms.InputTag("subjetsAK8","subjetAK8SmearedPt"),
                cms.InputTag("subjetsAK8","subjetAK8SmearedPEta"),
                cms.InputTag("subjetsAK8","subjetAK8SmearedPhi"),
                cms.InputTag("subjetsAK8","subjetAK8SmearedE"),
                cms.InputTag("subjetsAK8","subjetAK8JERup"),
                cms.InputTag("subjetsAK8","subjetAK8JERdown"),
                ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),
       cms.PSet(
            label = subjetCmsTopTaglabel,
            prefix = cms.string("subjetsCmsTopTag"),
            maxInstances = jetssize,
            variablesF = cms.VInputTag(
                # Basic
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagMass"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagPt"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagEta"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagY"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagPhi"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagE"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagCharge"),
                # subjetVars
                ### B-TAGGING
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagCSV"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagCSVV1"),
                ### GEN PARTON
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenPartonY"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenPartonEta"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenPartonPhi"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenPartonPt"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenPartonE"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenPartonCharge"),
                ###
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagPartonFlavour"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHadronFlavour"),
                ### GEN JET
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenJetY"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenJetEta"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenJetPhi"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenJetPt"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenJetE"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagGenJetCharge"),
                ### TRIGGER MATHING
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHLTjetEta"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHLTjetPhi"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHLTjetPt"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHLTjetE"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHLTjetDeltaR"),
                ### CONSTITUENTS
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagmuonMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagPhotonEnergy"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagElectronEnergy"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagMuonEnergy"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHFHadronEnergy"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHFEMEnergy"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagChargedHadronMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagnumberOfDaughters"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagchargedMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagneutralHadronMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagneutralHadronEnergyFraction"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagneutralEmEnergyFraction"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagchargedEmEnergyFraction"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagchargedHadronEnergyFraction"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagphotonMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagelectronMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHFHadronMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagHFEMMultiplicity"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagChargeMuEnergy"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagneutralMultiplicity"),
                #### FOR JEC
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagjecFactor0"),
                #### FOR SYSTEMATICS
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagSmearedPt"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagSmearedPEta"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagSmearedPhi"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagSmearedE"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagJERup"),
                cms.InputTag("subjetsCmsTopTag","subjetsCmsTopTagJERdown"),
                ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            ),


        cms.PSet(
            label = metlabel,
            prefix = cms.string("met"),
            maxInstances = cms.untracked.int32(1),
            variablesF = cms.VInputTag(
                cms.InputTag("met","metPt"),
                cms.InputTag("met","metPx"),
                cms.InputTag("met","metPy"),
                cms.InputTag("met","metPhi"),
                ),
            variablesI = cms.VInputTag(),
            singleI = cms.VInputTag(),
            singleF = cms.VInputTag(),
            )
        )
    )

